# Generated by Django 2.1.5 on 2021-04-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                 ('name', models.CharField(max_length=255, null=False)),
                # ('bank_data', models.ForeignKey(
                #     'client.Bank',  verbose_name="Banco", related_name="bank", on_delete=models.CASCADE)),
                (
                     'cvc', models.CharField(max_length=3, null=True,
                                             blank=True, verbose_name="CVC")), (
                     'dt_valid', models.CharField(max_length=15, null=True,
                                                  blank=True, verbose_name="Validade cartão")), (
                     'phone', models.CharField(
                         max_length=15, verbose_name="Número celular", blank=True)), (
                     'cpf', models.CharField(max_length=15, null=True,
                                             blank=True, verbose_name="CPF", unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('label', models.CharField(max_length=255, null=False)),
                ('accountTypeLabel', models.CharField(
                    max_length=255, verbose_name="Tipo de conta", null=True, blank=True)),
                ('accountNumber', models.CharField(
                    max_length=255, verbose_name="Número da conta", null=True, blank=True))
            ],
        ),
    ]
