# Generated by Django 2.1.5 on 2021-04-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210421_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bank',
            field=models.ManyToManyField(blank=True, null=True, related_name='bank', to='client.Bank', verbose_name='Banco'),
        ),
    ]
