# Generated by Django 2.1.5 on 2021-04-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20210421_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bank',
        ),
        migrations.AddField(
            model_name='client',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='client.Bank', verbose_name='Banco'),
            preserve_default=False,
        ),
    ]
