# Generated by Django 2.1.5 on 2021-04-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installments', models.PositiveIntegerField(blank=True, null=True, verbose_name='parcelas')),
                ('installmentInterest', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='juros parcelado')),
                ('installmentValue', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='valor da parcela')),
                ('fullValue', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='valor total')),
                ('comission', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='comissão')),
            ],
        ),
        migrations.CreateModel(
            name='RateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('installments', models.ManyToManyField(to='installments.Installments', verbose_name='Juros')),
            ],
        ),
    ]
