# Generated by Django 2.1.5 on 2021-04-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('installments', models.PositiveIntegerField(
                    null=True, blank=True, verbose_name="parcelas")),
                ('installmentInterest', models.DecimalField(
                    max_digits=6, decimal_places=2, null=True, blank=True, verbose_name="juros parcelado")),
                ('installmentValue', models.DecimalField(
                    max_digits=6, decimal_places=2, null=True, blank=True, verbose_name="valor da parcela")),
                ('fullValue', models.DecimalField(
                    max_digits=6, decimal_places=2, null=True, blank=True, verbose_name="valor total")),
                ('comission', models.DecimalField(
                    max_digits=6, decimal_places=2, null=True, blank=True, verbose_name="comissão"))
            ],
        ),
        migrations.CreateModel(
            name='RateTable',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('installments', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='client.Bank')),
            ],
        ),
    ]
