# Generated by Django 2.1.5 on 2021-04-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratetable', '0002_auto_20210421_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratetable',
            name='installments',
        ),
        migrations.AddField(
            model_name='ratetable',
            name='installments',
            field=models.ManyToManyField(blank=True, null=True, to='ratetable.Installments', verbose_name='Juros'),
        ),
    ]
