# Generated by Django 2.1.5 on 2021-04-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratetable', '0003_auto_20210421_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetable',
            name='installments',
            field=models.ManyToManyField(to='ratetable.Installments', verbose_name='Juros'),
        ),
    ]
