# Generated by Django 2.1.5 on 2021-04-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('accountTypeLabel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de conta')),
                ('accountNumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da conta')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cvc', models.CharField(blank=True, max_length=3, null=True, verbose_name='CVC')),
                ('dt_valid', models.CharField(blank=True, max_length=15, null=True, verbose_name='Validade cartão')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Número celular')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='clients.Bank', verbose_name='Banco')),
            ],
        ),
    ]
