# Generated by Django 2.1.5 on 2021-04-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='installmentValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor da parcela'),
        ),
    ]
